from typing import Protocol


class RenderSink(Protocol):
    async def write_thinking(self, text: str) -> None: ...
    async def write_answer(self, text: str) -> None: ...
    async def show_tool_call(self, name: str, args: str) -> None: ...
    async def finish(self) -> None: ...
