from typing import Protocol


class ToolCallSink(Protocol):
    async def write_args(self, chunk: str) -> None: ...
    async def show_result(self, result: str) -> None: ...


class RenderSink(Protocol):
    async def write_thinking(self, text: str) -> None: ...
    async def write_answer(self, text: str) -> None: ...
    async def start_tool_call(self, name: str) -> ToolCallSink: ...
    async def finish(self) -> None: ...
